version: "3.7"
services:
  backend:
    container_name: backend
    ports:
      - 4444:4444
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules
  frontend:
    container_name: frontend
    ports:
      - 7777:7777
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
